Análisis exploratorio de la brecha salarial de Género en México con datos de la ENIGH de 2010 a 2025 por promedio anual.

Expoloración de datos

In [ ]:
# Exploración de datos
import pandas as pd
df_genero = pd.read_csv("data/salario_genero.csv")

df_genero.columns
df_genero.shape
df_genero.dtypes

<bound method NDFrame.describe of     Nation ID  Nation  Quarter ID  Quarter  Sex ID     Sex  Monthly Wage  \
0         mex  México       20101  2010-Q1       1  Hombre   4048.124001
1         mex  México       20101  2010-Q1       2   Mujer   3037.057223
2         mex  México       20102  2010-Q2       1  Hombre   3979.107922
3         mex  México       20102  2010-Q2       2   Mujer   3052.803053
4         mex  México       20103  2010-Q3       1  Hombre   3901.177221
..        ...     ...         ...      ...     ...     ...           ...
115       mex  México       20243  2024-Q3       2   Mujer   5391.139285
116       mex  México       20244  2024-Q4       1  Hombre   6607.577274
117       mex  México       20244  2024-Q4       2   Mujer   5217.921972
118       mex  México       20251  2025-Q1       1  Hombre   6573.454827
119       mex  México       20251  2025-Q1       2   Mujer   5158.636867

     Workforce           Time
0     28421331  1265004000000
1     17103008  1265004000000
2     29057210  1272690000000
3     17540414  1272690000000
4     28982757  1280638800000
..         ...            ...
115   24272864  1722492000000
116   34924786  1730440800000
117   24562760  1730440800000
118   34976135  1738389600000
119   24024874  1738389600000

[120 rows x 9 columns]>

In [3]:
# Exploración de datos
df_genero.head()
df_genero.info()
df_genero.describe()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Nation ID     120 non-null    str
 1   Nation        120 non-null    str
 2   Quarter ID    120 non-null    int64
 3   Quarter       120 non-null    str
 4   Sex ID        120 non-null    int64
 5   Sex           120 non-null    str
 6   Monthly Wage  120 non-null    float64
 7   Workforce     120 non-null    int64
 8   Time          120 non-null    int64
dtypes: float64(1), int64(4), str(4)
memory usage: 8.6 KB

         Quarter ID      Sex ID  Monthly Wage     Workforce          Time
count    120.000000  120.000000    120.000000  1.200000e+02  1.200000e+02
mean   20173.316667    1.500000   4204.895991  2.637467e+07  1.500140e+12
std       44.405879    0.502096    975.366776  6.328439e+06  1.401940e+11
min    20101.000000    1.000000   2940.271308  1.707132e+07  1.265004e+12
25%    20133.750000    1.000000   3326.547858  1.989874e+07  1.381298e+12
50%    20172.500000    1.500000   4049.861505  2.658538e+07  1.497589e+12
75%    20212.250000    2.000000   4702.387299  3.224473e+07  1.621832e+12
max    20251.000000    2.000000   6854.283894  3.826931e+07  1.738390e+12

In [7]:
df_genero["Sex"].unique()

<StringArray>
['Hombre', 'Mujer']
Length: 2, dtype: str

In [8]:
df_genero["Quarter"].unique()

<StringArray>
['2010-Q1', '2010-Q2', '2010-Q3', '2010-Q4', '2011-Q1', '2011-Q2', '2011-Q3',
 '2011-Q4', '2012-Q1', '2012-Q2', '2012-Q3', '2012-Q4', '2013-Q1', '2013-Q2',
 '2013-Q3', '2013-Q4', '2014-Q1', '2014-Q2', '2014-Q3', '2014-Q4', '2015-Q1',
 '2015-Q2', '2015-Q3', '2015-Q4', '2016-Q1', '2016-Q2', '2016-Q3', '2016-Q4',
 '2017-Q1', '2017-Q2', '2017-Q3', '2017-Q4', '2018-Q1', '2018-Q2', '2018-Q3',
 '2018-Q4', '2019-Q1', '2019-Q2', '2019-Q3', '2019-Q4', '2020-Q1', '2020-Q3',
 '2020-Q4', '2021-Q1', '2021-Q2', '2021-Q3', '2021-Q4', '2022-Q1', '2022-Q2',
 '2022-Q3', '2022-Q4', '2023-Q1', '2023-Q2', '2023-Q3', '2023-Q4', '2024-Q1',
 '2024-Q2', '2024-Q3', '2024-Q4', '2025-Q1']
Length: 60, dtype: str

In [9]:
df_genero["Time"].unique()

array([1265004000000, 1272690000000, 1280638800000, 1288591200000,
       1296540000000, 1304226000000, 1312174800000, 1320127200000,
       1328076000000, 1335848400000, 1343797200000, 1351749600000,
       1359698400000, 1367384400000, 1375333200000, 1383285600000,
       1391234400000, 1398920400000, 1406869200000, 1414821600000,
       1422770400000, 1430456400000, 1438405200000, 1446357600000,
       1454306400000, 1462078800000, 1470027600000, 1477980000000,
       1485928800000, 1493614800000, 1501563600000, 1509516000000,
       1517464800000, 1525150800000, 1533099600000, 1541052000000,
       1549000800000, 1556686800000, 1564635600000, 1572588000000,
       1580536800000, 1596258000000, 1604210400000, 1612159200000,
       1619845200000, 1627794000000, 1635746400000, 1643695200000,
       1651381200000, 1659330000000, 1667282400000, 1675231200000,
       1682920800000, 1690869600000, 1698818400000, 1706767200000,
       1714543200000, 1722492000000, 1730440800000, 1738389600000])

In [11]:
df_genero.groupby("Sex")["Monthly Wage"].describe()

,count,mean,std,min,25%,50%,75%,max
Sex,,,,,,,,
Hombre,60.0,4716.575604,914.103454,3814.950625,4013.575563,4272.760893,5306.883162,6854.283894
Mujer,60.0,3693.216378,742.100270,2940.271308,3128.991485,3314.922490,4242.903643,5391.139285

In [15]:
df_genero.groupby(["Time","Sex"])["Monthly Wage"].mean()

Time           Sex
1265004000000  Hombre    4048.124001
               Mujer     3037.057223
1272690000000  Hombre    3979.107922
               Mujer     3052.803053
1280638800000  Hombre    3901.177221
                            ...
1722492000000  Mujer     5391.139285
1730440800000  Hombre    6607.577274
               Mujer     5217.921972
1738389600000  Hombre    6573.454827
               Mujer     5158.636867
Name: Monthly Wage, Length: 120, dtype: float64